dm/src/Entity/Serie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SerieRepository")
 */
class Serie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $annee_debut;

    /**
     * @ORM\Column(type="string", length=11)
     */
    private $annee_fin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $img;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_saisons;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie")
     * @ORM\JoinColumn(nullable=false, onDelete="SET NULL")
     */
    private $categorie_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAnneeDebut(): ?int
    {
        return $this->annee_debut;
    }

    public function setAnneeDebut(int $annee_debut): self
    {
        $this->annee_debut = $annee_debut;

        return $this;
    }

    public function getAnneeFin(): ?string
    {
        return $this->annee_fin;
    }

    public function setAnneeFin(string $annee_fin): self
    {
        $this->annee_fin = $annee_fin;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getNbSaisons(): ?int
    {
        return $this->nb_saisons;
    }

    public function setNbSaisons(int $nb_saisons): self
    {
        $this->nb_saisons = $nb_saisons;

        return $this;
    }

    public function getCategorieId(): ?Categorie
    {
        return $this->categorie_id;
    }

    public function setCategorieId(?Categorie $categorie_id): self
    {
        $this->categorie_id = $categorie_id;

        return $this;
    }
}

dm/src/Controller/DefaultController.php
<?php
    namespace App\Controller;
    
    use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
    use Symfony\Component\Routing\Annotation\Route;
    use App\Entity\Categorie;
    use App\Entity\Serie;
    use App\Form\CategorieType;
    use Symfony\Contracts\Translation\TranslatorInterface;

    use Symfony\Component\HttpFoundation\Request;

    class DefaultController extends AbstractController{
        /**
         * @Route("/", name="home")
         */
        public function index(Request $request){
            $em = $this->getDoctrine()->getManager();

            $categorie = new Categorie();

            $form = $this->createForm(CategorieType::class, $categorie);

            $form->handleRequest($request);

            if($form->isSubmitted() && $form->isValid()){
                // $datas = $form->getData();

                $em->persist($categorie);
                $em->flush();
            }

            $categorie = $em->getRepository(Categorie::class)->findAll();
            $series = $em->getRepository(Serie::class)->findAll();

            return $this->render('default/index.html.twig', [
                'categorie' => $categorie,
                'series' => $series,
                'add_categorie' => $form->createView()
            ]);
        }

        /**
         * @Route("/categorie/{id}", name="categorie")
         */
        public function categorie(Categorie $categorie, Request $request){
            $form = $this->createForm(CategorieType::class, $categorie);
    
            $form->handleRequest($request);
    
            if($form->isSubmitted() && $form->isValid()){
                $em = $this->getDoctrine()->getManager();
                $em->persist($categorie);
                $em->flush();
            }
    
            return $this->render('default/categorie.html.twig',
                array(
                    'categorie'  => $categorie,
                    'edit_form' => $form->createView()
                )
            );
        }

        /**
         * @Route("/categorie/delete/{id}", name="categorieDelete") 
         */
        public function CategorieDelete(Categorie $categorie = null){
            if($categorie != null){
                $em = $this->getDoctrine()->getManager();
                $em->remove($categorie);
                $em->flush();
            }
    
            return $this->redirectToRoute('home');
        }
    }
?>

dm/templates/default/categorie.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<h1>Fiche catégorie</h1>
	<br>
	<h3>Nom de la catégorie : {{categorie.name}}</h3>
	<br>
	<h4>Modifier la tâche</h4>
	{{ form(edit_form) }}
	<br>
	<a href="{{ path('categorieDelete', {'id': categorie.id}) }}">Supprimer cette catégorie</a>
{% endblock %}

dm/templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}
    <h2>Section Série</h2>
    <p>{{ series|length }} séries sont disponibles sur ce site !</p>
    <a href="{{ path('series') }}">Aller vers la page des séries</a>
    <h2>Section catégorie</h2>
    <p>Notre choix de séries s'étant parmi {{ categorie|length }} catégories différentes !</p>
    {% if categorie is empty %}
        <p>Il n'y a aucune catégorie</p>
    {% else %}
        <table class="table table-striped">
            <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Nombre de séries</th>
                    </tr>
                </thead>
                <tbody>
                {% for categories in categorie %}
                <tr>
                    <td>
                        <a href="{{ path('categorie', {'id': categories.id}) }}" title="{{ categories.name }}">
                            {{ categories.name }}
                        </a>
                    </td>
                    <td>
                        {% set count = 0 %}
                        {% for serie in series if serie.categorieId == categories %}
                        {% set count = count + 1 %}
                        {% endfor %}
                        {{ count }}
                    </td>
                    <td>
                        <a href="{{ path('categorieDelete', {'id': categories.id}) }}">X</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </thead>
        </table>
    {% endif %}

    <h2>Ajouter une catégorie</h2>
        {{ form_start(add_categorie) }}
            {{ form_row(add_categorie.name) }}
        {{ form_end(add_categorie) }}

{% endblock %}